[tool.poetry]
name = "carrier.fedex"
version = "2020.3.1"
description = "FedEx Web API Schemas Python Data Types library"
repository="https://github.com/karrioapi/karrio"
homepage="https://github.com/karrioapi/karrio/tree/main/schemas/fedex"
authors = ["Karrio <hello@karrio.io>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "fedex_lib" }
]
classifiers = [
	"Intended Audience :: Developers",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]

[tool.poetry.dependencies]
python = "^3.6"
six = ""
lxml = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools!=50.0"]
build-backend = "poetry.core.masonry.api"
